name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      vault_name:
        description: 'Name of the Recovery Services Vault'
        required: true
        default: 'vault-prod-001'

jobs:
  terraform-format:
    name: Terraform Format
    runs-on: ubuntu-latest
    # environment: production
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          # cli_config_credentials_hostname: app.terraform.io
          # cli_config_credentials_username: ${{ secrets.TF_API_USERNAME }}
          # cli_config_credentials_password: ${{ secrets.TF_API_PASSWORD }}
          # cli_config_credentials_organization: ${{ secrets.TF_API_ORG }}

      - name: Terraform Init
        run: terraform init 
        
      - name: Terraform Format
        run: terraform fmt -check -recursive
